on:
  push:
    branches: [main, master]
    paths-ignore:
      - ".github/badges/coverage.svg"
  pull_request:

name: coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  coverage:
    uses: pedrobtz/r-actions/.github/workflows/coverage.yml@bdfde5edd37f25b33af142a4a881585e77bda3c2 # v1.22.0
    permissions:
      contents: write
